// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EmptyCmp: typeof import('./src/components/empty-cmp.vue')['default']
    LayerTree: typeof import('./src/components/LayerTree.vue')['default']
    MapNavCompassOblique: typeof import('./src/components/navigation/MapNavCompassOblique.vue')['default']
    MapNavCompassRegular: typeof import('./src/components/navigation/MapNavCompassRegular.vue')['default']
    MapNavigation: typeof import('./src/components/navigation/MapNavigation.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PopoverManager: typeof import('./src/modules/popover-manager/PopoverManager.vue')['default']
    ToolboxManager: typeof import('./src/modules/toolbox-manager/ToolboxManager.vue')['default']
    ToolboxMultiSelectButton: typeof import('./src/modules/toolbox-manager/ToolboxMultiSelectButton.vue')['default']
    ToolboxSingleSelectButton: typeof import('./src/modules/toolbox-manager/ToolboxSingleSelectButton.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VcsApp: typeof import('./src/components/VcsApp.vue')['default']
    VcsCompass: typeof import('./src/components/navigation/VcsCompass.vue')['default']
    VcsMap: typeof import('./src/components/VcsMap.vue')['default']
    VcsZoomButton: typeof import('./src/components/navigation/VcsZoomButton.vue')['default']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarItems: typeof import('vuetify/lib')['VToolbarItems']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
    VTreeview: typeof import('vuetify/lib')['VTreeview']
    WindowComponent: typeof import('./src/modules/window-manager/WindowComponent.vue')['default']
    WindowComponentHeader: typeof import('./src/modules/window-manager/WindowComponentHeader.vue')['default']
    WindowManager: typeof import('./src/modules/window-manager/WindowManager.vue')['default']
  }
}

export { }
