<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <g id="Group_846" transform="translate(0.5 0.5)">
      <circle
        id="Ellipse_87"
        cx="4"
        cy="4"
        r="4"
        transform="translate(3)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <path
        id="Path_436"
        d="M14.5,15.5v-4a1,1,0,0,0-1-1H1.5a1,1,0,0,0-1,1v12"
        transform="translate(-0.5 -0.5)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <path
        id="Path_437"
        d="M23.5,23.5v-7a1,1,0,0,0-1-1h-12a1,1,0,0,0-1,1v7"
        transform="translate(-0.5 -0.5)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_135"
        x2="8"
        transform="translate(3 13)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_136"
        x2="6"
        transform="translate(3 16)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_137"
        x2="6"
        transform="translate(3 19)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_138"
        y2="4"
        transform="translate(7 2)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_139"
        x1="4"
        transform="translate(5 4)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_140"
        y2="2"
        transform="translate(7 8)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_141"
        x2="23"
        transform="translate(0 23)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <rect
        id="Rectangle_732"
        width="2"
        height="2"
        transform="translate(15 21)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_142"
        x2="1"
        transform="translate(11 19)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_143"
        x1="1"
        transform="translate(11 17)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_144"
        x2="1"
        transform="translate(14 19)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_145"
        x1="1"
        transform="translate(14 17)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_146"
        x2="1"
        transform="translate(17 19)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_147"
        x1="1"
        transform="translate(17 17)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_148"
        x2="1"
        transform="translate(20 19)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
      <line
        id="Line_149"
        x1="1"
        transform="translate(20 17)"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="1"
      />
    </g>
  </svg>
</template>
