name: Deploy GH Pages
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-v6.1
jobs:
  lux-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - run: npm run build

      - name: deploy to gh pages
        run: |
          echo "Deploying to directory: ${{env.BRANCH_NAME}}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npx gh-pages --dist dist/ --dest ${{env.BRANCH_NAME}} --remove "${{env.BRANCH_NAME}}/**" --no-history --dotfiles --repo "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"

      - name: add PR comment
        uses: thollander/actions-comment-pull-request@v1
        if: github.event_name == 'pull_request'
        with:
          message: 'GitHub Pages links: https://geoportail-luxembourg.github.io/3dviewer/${{env.BRANCH_NAME}}/'
          comment_includes: 'GitHub Pages links:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
